# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/notes-app-repo/notes-app:${COMMIT_SHA}',
    './app'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: [
    'push',
    'us-central1-docker.pkg.dev/${PROJECT_ID}/notes-app-repo/notes-app:${COMMIT_SHA}'
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to Cloud Run'
  entrypoint: gcloud
  args: [
    'run',
    'deploy', 'notes-app-service-clean', # New Cloud Run service name
    '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/notes-app-repo/notes-app:${COMMIT_SHA}',
    '--region', 'us-central1', # Specify your desired region
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID}', # Set project ID as env var
    '--quiet'
  ]

images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/notes-app-repo/notes-app:${COMMIT_SHA}'
options:
   logging: CLOUD_LOGGING_ONLY
